name: release
on:
  push:
    branches:
      - main
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        uses: onichandame/node-test-action@0.0.1
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: false
  release:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: yarn && yarn build
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: false # allow the creation of yarn.lock
      - name: Publish
        uses: onichandame/github-action-npm-publish@v0.1.7
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
